### ISSUE TITLE
Could recent files be added to some future update?

### ISSUE THREAD

**Issue by Sauron0** [flathub/org.kde.haruna#1]
I just installed Haruna video player.  Very clean interface, works great.  IMHO the only thing missing is an open recent files option.

Could this be added in some future update?

**Comment by tsdgeos** [comment]
Please file wishes at https://bugs.kde.org/enter_bug.cgi?product=Haruna 

This is just for the flathub packaging not for the app development itself

**Comment by Sauron0** [comment]
Apologies.  My bad.
