### ISSUE TITLE
haruna 1.2.1 flatpak update error 

### ISSUE THREAD

**Issue by cappelikan** [flathub/org.kde.haruna#108]
![Знімок_20241120_061839](https://github.com/user-attachments/assets/c4c34252-d074-488a-922b-da883611cf5b)
While trying to apply extra data: Apply_extra script error, exit status 256

**Comment by g-fb** [comment]
If it's an update error you should report it to flathub (or whatever flatpak remote you use) or your distro.

**Comment by g-fb** [comment]
You could also try to update from the command line `flatpak update --verbose` maybe it will give more info.
