### ISSUE TITLE
Setting JPEG XL as a format for screenshots produces 0 bytes empty screenshot files

### ISSUE THREAD

**Issue by iamalexei** [flathub/org.kde.haruna#17]
OS: Debian 12 Bookworm,
Arch: x86_64,
Version: 0.11.1,
Runtime: org.kde.Platform/x86_64/5.15-22.08,
Sdk: org.kde.Sdk/x86_64/5.15-22.08

**Comment by Justinzobel** [comment]
Can confirm on Flatpak but not on RPM Haruna. Need to investigate.

**Comment by iamalexei** [comment]
The issue was fixed in the latest update. Thank you!
